version: '3.8'
services:
  db:
    env_file: .env
    image: postgres:14.1-alpine
    container_name: dona-backend
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '6000:5432'
    volumes: 
      - db:/var/lib/postgresql/datadoc
volumes:
  db:
    driver: local
    